### ISSUE TITLE
Scripts sometimes dont execute

### ISSUE THREAD

**Issue by robbaerdaeper** [hayaunderscore/oveninjector#2]
While Porting one of my toppinloader mods and making another mod i noticed that sometimes scripts dont execute themselves. I have no idea if this is because one of my scripts has a coding error or anything. Ill drop a file for you to debug.
[dumbass's chaos mod.zip](https://github.com/hayaunderscore/oveninjector/files/15100159/dumbass.s.chaos.mod.zip)

**Comment by hayaunderscore** [comment]
First off, I recommend moving `randomize()` to `init.gml` or just not using it at all.

`random_range()` provides a _**Real**_ value, meaning it can be a fraction, like 0.5 and 2.3. If you want a normal integer just use `irandom_range()`.

Also your gui script is named incorrectly. It should just be `gui.gml` as stated by the documentation.
