### ISSUE TITLE
crash with custom and startup

### ISSUE THREAD

**Issue by explosionenjoyer** [hayaunderscore/oveninjector#4]
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object obj_textureloading:

File is not opened for reading.
at gml_Script_lang_parse_file
############################################################################################
gml_Script_lang_parse_file (line -1)
gml_Script_scr_get_languages
gml_Object_obj_textureloading_Create_0

**Comment by hayaunderscore** [comment]
Please revert your language files via `Verify integrity of game files...` on Steam.

**Comment by explosionenjoyer** [comment]
tried that, did nothing and the lang file was in English in the first place
